[[redirects]]
  from = "/relay-dlLN/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/relay-dlLN/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true
